sudo: false
language: android
jdk: oraclejdk8
android:
  components:
# first 'tools' updates SDK tools 'til last version ** in remote repository number 10 **
  - tools
# second 'tools' updates SDK tools 'til last version ** in remote repository number 11 ** (current last one)
  - tools
  - platform-tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-23
before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI -c 20M
  - emulator -avd test -no-skin -no-audio -no-window &
  - chmod +x ./wait_for_emulator.sh
  - ./wait_for_emulator.sh
script:
# build app and assemble APK, in debug mode
  - ./gradlew assembleDebug
env:
  matrix:
  - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a